# config.yaml
app:
  title: "Heavy Metal Pollution Indices Calculator"
  version: "1.0.0"
  author: "Environmental Data Analytics Team"
  description: "Automated calculation of Heavy Metal Pollution Indices for groundwater quality assessment"
  
standards:
  default_source: "WHO"
  custom_standards_allowed: true
  sources:
    WHO:
      As: 0.01
      Cd: 0.003
      Cr: 0.05
      Cu: 2.0
      Fe: 0.3
      Mn: 0.4
      Ni: 0.07
      Pb: 0.01
      Zn: 3.0
    EPA:
      As: 0.01
      Cd: 0.005
      Cr: 0.1
      Cu: 1.3
      Fe: 0.3
      Mn: 0.05
      Ni: 0.1
      Pb: 0.015
      Zn: 5.0
  
data:
  max_upload_size: 200  # MB
  supported_formats: ["csv", "xlsx", "xls"]
  required_metals_minimum: 2
  sample_data_size: 50
  
visualization:
  default_theme: "plotly"
  color_scheme: "environmental"
  plot_height: 500
  plot_width: 700
  
reports:
  default_format: "markdown"
  include_charts: true
  include_maps: true
  include_statistics: true
  sections:
    - "Executive Summary"
    - "Methodology" 
    - "Results Analysis"
    - "Quality Assessment"
    - "Statistical Analysis"
    - "Geospatial Analysis"
    - "Conclusions"
    - "Recommendations"
  
geospatial:
  default_map_provider: "OpenStreetMap"
  clustering_enabled: true
  heatmap_enabled: true
  marker_size_range: [5, 20]
  
quality_categories:
  excellent:
    range: [0, 25]
    color: "#2E8B57"
    description: "Safe for drinking with no treatment"
  good:
    range: [25, 50]
    color: "#32CD32"
    description: "Safe for drinking with minimal treatment"
  poor:
    range: [50, 100]
    color: "#FFD700"
    description: "Requires treatment before consumption"
  very_poor:
    range: [100, 200]
    color: "#FF6347"
    description: "Extensive treatment required"
  unsuitable:
    range: [200, 1000]
    color: "#DC143C"
    description: "Not suitable for drinking purposes"
  hazardous:
    range: [1000, float('inf')]
    color: "#8B0000"
    description: "Highly contaminated and unsafe for any use"
    